# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase_entry',
            name='data_end',
            field=models.DateField(blank=True),
        ),
    ]
