# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170327_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
