# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_group_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phase_entry',
            old_name='data_end',
            new_name='date_end',
        ),
    ]
