# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170405_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='light',
            old_name='data_end',
            new_name='date_end',
        ),
    ]
