# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 14:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20170408_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='heat',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(40)]),
        ),
    ]
